// Matches proto/hits.proto (mandate.x402.v1.Hits). Regenerated by
// `substreams protogen` if the proto changes; keep this file in lockstep.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hits {
    #[prost(uint64, tag = "1")]
    pub block: u64,
    #[prost(string, repeated, tag = "2")]
    pub txs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
